# Shelf configuration
cabinets:
  - cabinet_controller_id: 25002
    # Middle of bottom shelf. Coordinates in feet
    location: (87.42, 13.0, 0.396)
    zone: "Zone1"
    shelf_height: 1.0
    shelf_width: 2.66
    height_proximity_threshold: 1.5
    width_proximity_threshold: 0.5
  - cabinet_controller_id: 25001
    # Bottom of bottom shelf. Coordinates in feet
    # Middle of bottom shelf. Coordinates in feet
    location: (93.0, 13.0, 0.396)
    zone: "Zone2"
    shelf_height: 1.0
    shelf_width: 2.66
    height_proximity_threshold: 1.5
    width_proximity_threshold: 0.5




# LED color codes
led_colors:
  initial: "red"
  rfid_match: "blue"
  rfid_miss: "white"
  off: "off"

# Delay before turning off LED (in seconds)
led_timeout: 5

# Network settings
network:
  #geotraqr_address: 10.10.10.172
  # geo_data_port: 50361
  # geo_cmd_port: 50362
  geotraqr_address: 25.100.38.191
  geo_data_port: 50531
  geo_cmd_port: 50532
